### ISSUE TITLE
How to not use ssl?

### ISSUE THREAD

**Issue by hopewise** [stevenosloan/slack-notifier#135]
Currently we have `OpenSSL::SSL::SSLError` error as below, and we have contacted Slack to check for their certificate, they said here https://status.slack.com/2023-03/27c0f9229399a532 that some users would have such issue.

Is there an option to not use ssl ? we tried [here](https://github.com/slack-notifier/slack-notifier/blob/main/lib/slack-notifier/util/http_client.rb#L59) to hardcode it as false, but did not work..

Any idea how to skip handshake for https?

```
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed
	from /home/deploy/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock'
	from /home/deploy/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:933:in `connect'
	from /home/deploy/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
	from /home/deploy/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:852:in `start'
	from /home/deploy/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/net/http.rb:1398:in `request'
	from /var/www/backend/shared/bundle/ruby/2.3.0/gems/slack-notifier-2.3.2/lib/slack-notifier/util/http_client.rb:27:in `call'
	from /var/www/backend/shared/bundle/ruby/2.3.0/gems/slack-notifier-2.3.2/lib/slack-notifier/util/http_client.rb:13:in `post'
	from /var/www/backend/shared/bundle/ruby/2.3.0/gems/slack-notifier-2.3.2/lib/slack-notifier.rb:49:in `block in post'
	from /var/www/backend/shared/bundle/ruby/2.3.0/gems/slack-notifier-2.3.2/lib/slack-notifier.rb:47:in `map'
	from /var/www/backend/shared/bundle/ruby/2.3.0/gems/slack-notifier-2.3.2/lib/slack-notifier.rb:47:in `post'
	from /var/www/backend/shared/bundle/ruby/2.3.0/gems/slack-notifier-2.3.2/lib/slack-notifier.rb:37:in `ping'

```

**Comment by samdking** [comment]
I'm having the same problem, as of today.

**Comment by marcelwooga** [comment]
I have the same issue on my machine, you could bypass certificate validation by adding this, but **I do not recommend** doing it on production:
`OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE`

Also I don't think it's an issue with this gem, if I run this code, it also fails for me:
```
require 'net/http'

uri = URI::HTTPS.build(host: 'slack.com') # works for e.g. google.com
res = Net::HTTP.start(uri.host, uri.port, use_ssl: true)
cert = res.peer_cert
p cert
```

**Comment by davidbodow-st** [comment]
I haven't dug into any example requests from the particular endpoints this gem uses itself, but `api.slack.com` [sets HSTS headers](https://securityheaders.com/?q=api.slack.com&followRedirects=on) and [also has preloaded HSTS registered](https://hstspreload.org/?domain=api.slack.com), so IMO it would be inappropriate for the client to support insecure HTTP (if their server even accepts it, which I would doubt: I do see a permanent 301 to HTTPS with `curl --verbose http://api.slack.com`)

All indications are that the client should only be using secure connection methods, so IMO it's better for this gem to respect those signals. If Slack misconfigures their certs, that's downtime for them, not something that the client should be expected to handle.

**Comment by hopewise** [comment]
I have fixed the issue with this initializer, to fallback to `OpenSSL::SSL::VERIFY_NONE` incase of an exception, its working, but I know there should be a better solution.

```
module Slack
  class Notifier
    def ping message, options={}
      if message.is_a?(Hash)
        options = message
      else
        options[:text] = message
      end

      begin
        post options
      rescue => e

        OpenSSL::SSL.const_set('VERIFY_PEER', OpenSSL::SSL::VERIFY_NONE)
        post options
        OpenSSL::SSL.const_set('VERIFY_PEER', OpenSSL::SSL::VERIFY_PEER)

      end

    end
  end
end
```

**Comment by MadWagon** [comment]
Same problem here, has anyone found a solution ? @hopewise solution is not working for us

**Comment by hopewise** [comment]
@MadWagon make that this code use reached when rails boots, ex: `config/initializers/slack.rb`

**Comment by MadWagon** [comment]
Yes this is exactly what I did, even traced that the exception is raised and that rescue code is executed, but still getting the same error after the const is changed. I believe it's related to the version of openssl which is on the production server (v1), as hinted in the Slack status https://status.slack.com/2023-03-14. Can I ask what version of openssl you have ?

**Comment by MadWagon** [comment]
Yes this is exactly what I did, even traced that the exception is raised
and that rescue code is executed, but still getting the same error after
the const is changed. I believe it's related to the version of openssl
which is on the production server (v1), as hinted in the Slack status
https://status.slack.com/2023-03-14. Can I ask what version of openssl you
have ?

Le dim. 19 mars 2023 à 13:44, Samir Sabri ***@***.***> a
écrit :

**Comment by hopewise** [comment]
I've checked on rails app level:

```
$ > OpenSSL::OPENSSL_LIBRARY_VERSION
 => "OpenSSL 1.0.2g  1 Mar 2016"
```

and on OS level to make sure:

```
$ openssl version
OpenSSL 1.0.2g  1 Mar 2016
```

I hope that helps.

**Comment by MadWagon** [comment]
I am also using the same exact version of OpenSSL 1.0.2g, so I don't know what to do now :( 

Thanks though

**Comment by marcelwooga** [comment]
I did some further testing and figured out that we were using another Gem called `certified` which is using its own certificates, after removing it the Slack notifier works again.

**Comment by hopewise** [comment]
we use `certified` gem, but not directly..
```
ruby-bandwidth-iris (2.6.0)
      activesupport (>= 4.2.7)
      builder
      certified
      faraday
      faraday_middleware
      nori
```

**Comment by mzientkowski** [comment]
`notifier = Slack::Notifier.new URL, http_options: { verify_mode: OpenSSL::SSL::VERIFY_NONE }`

**Comment by MadWagon** [comment]
@mzientkowski this has no effect, still getting the ssl error, but thanks to you reading the code in slack-notifier.rb

`params[:http_options] = payload.delete(:http_options) if payload.key?(:http_options)` 

I figured out the way to make it work again, set the http_options in the payload of the ping method

**Comment by jspargo** [comment]
Anyone stumbling across this running into this issue when using slack-notifier in a Rails application on a Docker container using an old ruby image (e.g. `ruby-2.3.3`, `ruby-2.x`), adding this to my Dockerfile worked for me:
```
RUN sed -i '/^mozilla\/DST_Root_CA_X3/s/^/!/' /etc/ca-certificates.conf \
  && update-ca-certificates -f
```

Thanks to this blog for the full explanation and steps:
https://nickjanetakis.com/blog/fix-a-lets-encrypt-related-expired-root-certificate-on-an-old-server

**Comment by erdalkucukk** [comment]
Is there an update on this issue? Will it be implemented soon?

**Comment by CodySanders** [comment]
> Anyone stumbling across this running into this issue when using slack-notifier in a Rails application on a Docker container using an old ruby image (e.g. `ruby-2.3.3`, `ruby-2.x`), adding this to my Dockerfile worked for me:
> 
> ```
> RUN sed -i '/^mozilla\/DST_Root_CA_X3/s/^/!/' /etc/ca-certificates.conf \
>   && update-ca-certificates -f
> ```
> 
> Thanks to this blog for the full explanation and steps: https://nickjanetakis.com/blog/fix-a-lets-encrypt-related-expired-root-certificate-on-an-old-server

@jspargo Thanks so much, this was exactly what we needed!
